apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ns1
  namespace: ns1
  labels:
    kubernetes.io/day: "10"
    kubernetes.io/task: "1"
    kubernetes.io/type: "deployment"
    kubernetes.io/app: nginx
spec:
  selector:
    matchLabels:
      kubernetes.io/type: "pod"
      kubernetes.io/app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        kubernetes.io/type: "pod"
        kubernetes.io/app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        - targetPort: 8080
---


