apiVersion: v1
kind: Service
metadata:
  name: svc-ns2
  namespace: ns2
  labels:
    kubernetes.io/day: "10"
    kubernetes.io/task: "2"
    kubernetes.io/type: "service"
    kubernetes.io/app: nginx
spec:
  selector:
    kubernetes.io/type: "pod"
    kubernetes.io/app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---


